[package]
name = "fix-getters-rules"
version = "0.1.0"
authors = ["François Laignel <fengalin@free.fr>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
lazy_static = "1"

[features]
default = ["dir-entry"]

# dir_entry module.
dir-entry = []
